//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOR.Resources.FrontEndTranslations.Activities
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ActivityTimeCorrection
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ActivityTimeCorrection()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFC.Resources.Frontend.Activities.ActivityTimeCorrection", typeof(ActivityTimeCorrection).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Time corrections.
        /// </summary>
        internal static string activityTimeCorrections
        {
            get
            {
                return ResourceManager.GetString("activityTimeCorrections", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activity has been added successfully..
        /// </summary>
        internal static string addedSuccessfully
        {
            get
            {
                return ResourceManager.GetString("addedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is opened activity from  {{ overlappingActivityStartDate }}..
        /// </summary>
        internal static string openedOverlappingActivityValidationMessage
        {
            get
            {
                return ResourceManager.GetString("openedOverlappingActivityValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is activity from {{ overlappingActivityStartDate }} to {{ overlappingActivityEndDate}}..
        /// </summary>
        internal static string overlappingActivityValidationMessage
        {
            get
            {
                return ResourceManager.GetString("overlappingActivityValidationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activity has been updated successfully..
        /// </summary>
        internal static string saveSuccessfully
        {
            get
            {
                return ResourceManager.GetString("saveSuccessfully", resourceCulture);
            }
        }
    }
}
