//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOR.Resources.FrontEndTranslations.Common
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFC.Resources.Frontend.Common.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to False.
        /// </summary>
        internal static string _false
        {
            get
            {
                return ResourceManager.GetString("false", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to True.
        /// </summary>
        internal static string _true
        {
            get
            {
                return ResourceManager.GetString("true", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to perform this action..
        /// </summary>
        internal static string accessForbidden
        {
            get
            {
                return ResourceManager.GetString("accessForbidden", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string activate
        {
            get
            {
                return ResourceManager.GetString("activate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string active
        {
            get
            {
                return ResourceManager.GetString("active", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string add
        {
            get
            {
                return ResourceManager.GetString("add", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving data..
        /// </summary>
        internal static string anErrorOccuredWhileSaving
        {
            get
            {
                return ResourceManager.GetString("anErrorOccuredWhileSaving", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attached by.
        /// </summary>
        internal static string attachedBy
        {
            get
            {
                return ResourceManager.GetString("attachedBy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        internal static string attachments
        {
            get
            {
                return ResourceManager.GetString("attachments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string back
        {
            get
            {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string cancel
        {
            get
            {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string category
        {
            get
            {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string code
        {
            get
            {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string comment
        {
            get
            {
                return ResourceManager.GetString("comment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        internal static string control
        {
            get
            {
                return ResourceManager.GetString("control", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Correct.
        /// </summary>
        internal static string correct
        {
            get
            {
                return ResourceManager.GetString("correct", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Correction.
        /// </summary>
        internal static string correction
        {
            get
            {
                return ResourceManager.GetString("correction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Creation date.
        /// </summary>
        internal static string creationDate
        {
            get
            {
                return ResourceManager.GetString("creationDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string date
        {
            get
            {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to YYYY-MM-DD HH:MM.
        /// </summary>
        internal static string dateFormat
        {
            get
            {
                return ResourceManager.GetString("dateFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Deactivate.
        /// </summary>
        internal static string deactivate
        {
            get
            {
                return ResourceManager.GetString("deactivate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default value.
        /// </summary>
        internal static string defaultValue
        {
            get
            {
                return ResourceManager.GetString("defaultValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description
        {
            get
            {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string details
        {
            get
            {
                return ResourceManager.GetString("details", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Dictionary.
        /// </summary>
        internal static string dictionary
        {
            get
            {
                return ResourceManager.GetString("dictionary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string domain
        {
            get
            {
                return ResourceManager.GetString("domain", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to days.
        /// </summary>
        internal static string duration_days
        {
            get
            {
                return ResourceManager.GetString("duration.days", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to hrs.
        /// </summary>
        internal static string duration_hours
        {
            get
            {
                return ResourceManager.GetString("duration.hours", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to min.
        /// </summary>
        internal static string duration_minutes
        {
            get
            {
                return ResourceManager.GetString("duration.minutes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duration time.
        /// </summary>
        internal static string durationTime
        {
            get
            {
                return ResourceManager.GetString("durationTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string edit
        {
            get
            {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email
        {
            get
            {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string endDate
        {
            get
            {
                return ResourceManager.GetString("endDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        internal static string endTime
        {
            get
            {
                return ResourceManager.GetString("endTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entry author.
        /// </summary>
        internal static string entryAuthor
        {
            get
            {
                return ResourceManager.GetString("entryAuthor", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entry date.
        /// </summary>
        internal static string entryDate
        {
            get
            {
                return ResourceManager.GetString("entryDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        internal static string export
        {
            get
            {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to External name.
        /// </summary>
        internal static string externalName
        {
            get
            {
                return ResourceManager.GetString("externalName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Field type.
        /// </summary>
        internal static string fieldType
        {
            get
            {
                return ResourceManager.GetString("fieldType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to File is too large {{ fileSize }}MB: max {{ fileMaxSize }}MB.
        /// </summary>
        internal static string fileIsTooLarge
        {
            get
            {
                return ResourceManager.GetString("fileIsTooLarge", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string firstName
        {
            get
            {
                return ResourceManager.GetString("firstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string from
        {
            get
            {
                return ResourceManager.GetString("from", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string generate
        {
            get
            {
                return ResourceManager.GetString("generate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string group
        {
            get
            {
                return ResourceManager.GetString("group", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Is not active select different one.
        /// </summary>
        internal static string isNotActiveSelectDifferentOne
        {
            get
            {
                return ResourceManager.GetString("isNotActiveSelectDifferentOne", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        internal static string key
        {
            get
            {
                return ResourceManager.GetString("key", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        internal static string label
        {
            get
            {
                return ResourceManager.GetString("label", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string lastName
        {
            get
            {
                return ResourceManager.GetString("lastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lenght.
        /// </summary>
        internal static string lenght
        {
            get
            {
                return ResourceManager.GetString("lenght", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login
        {
            get
            {
                return ResourceManager.GetString("login", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name
        {
            get
            {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no
        {
            get
            {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is no attachments.
        /// </summary>
        internal static string noAttachments
        {
            get
            {
                return ResourceManager.GetString("noAttachments", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Is not active.
        /// </summary>
        internal static string notActiveObject
        {
            get
            {
                return ResourceManager.GetString("notActiveObject", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource not found: {{ url }}.
        /// </summary>
        internal static string notFoundProblem
        {
            get
            {
                return ResourceManager.GetString("notFoundProblem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No default value.
        /// </summary>
        internal static string noValue
        {
            get
            {
                return ResourceManager.GetString("noValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string number
        {
            get
            {
                return ResourceManager.GetString("number", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string order
        {
            get
            {
                return ResourceManager.GetString("order", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string ordinalNumber
        {
            get
            {
                return ResourceManager.GetString("ordinalNumber", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ownership.
        /// </summary>
        internal static string ownership
        {
            get
            {
                return ResourceManager.GetString("ownership", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string password
        {
            get
            {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string path
        {
            get
            {
                return ResourceManager.GetString("path", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string preview
        {
            get
            {
                return ResourceManager.GetString("preview", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Report quantities.
        /// </summary>
        internal static string qtyReportAllowed
        {
            get
            {
                return ResourceManager.GetString("qtyReportAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quantity required.
        /// </summary>
        internal static string qtyRequired
        {
            get
            {
                return ResourceManager.GetString("qtyRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string quantity
        {
            get
            {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quantity completed.
        /// </summary>
        internal static string quantityCompleted
        {
            get
            {
                return ResourceManager.GetString("quantityCompleted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Quantity rejected.
        /// </summary>
        internal static string quantityRejected
        {
            get
            {
                return ResourceManager.GetString("quantityRejected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reject reason.
        /// </summary>
        internal static string rejectReason
        {
            get
            {
                return ResourceManager.GetString("rejectReason", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        internal static string remarks
        {
            get
            {
                return ResourceManager.GetString("remarks", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string remove
        {
            get
            {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string required
        {
            get
            {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string save
        {
            get
            {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save and create new.
        /// </summary>
        internal static string saveAndCreateNew
        {
            get
            {
                return ResourceManager.GetString("saveAndCreateNew", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string search
        {
            get
            {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to --select--.
        /// </summary>
        internal static string select
        {
            get
            {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Select Worker.
        /// </summary>
        internal static string selectWorker
        {
            get
            {
                return ResourceManager.GetString("selectWorker", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A problem occured with getting response from server.
        /// </summary>
        internal static string serverResponseProblem
        {
            get
            {
                return ResourceManager.GetString("serverResponseProblem", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string signOut
        {
            get
            {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Site.
        /// </summary>
        internal static string site
        {
            get
            {
                return ResourceManager.GetString("site", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string startDate
        {
            get
            {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string startTime
        {
            get
            {
                return ResourceManager.GetString("startTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string status
        {
            get
            {
                return ResourceManager.GetString("status", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status reason.
        /// </summary>
        internal static string statusReason
        {
            get
            {
                return ResourceManager.GetString("statusReason", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string to
        {
            get
            {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string tools
        {
            get
            {
                return ResourceManager.GetString("tools", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string type
        {
            get
            {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UM.
        /// </summary>
        internal static string um
        {
            get
            {
                return ResourceManager.GetString("um", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Upload file.
        /// </summary>
        internal static string uploadFile
        {
            get
            {
                return ResourceManager.GetString("uploadFile", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code is not unique..
        /// </summary>
        internal static string validation_codeIsNotUnique
        {
            get
            {
                return ResourceManager.GetString("validation.codeIsNotUnique", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Duplicated entry for selected object..
        /// </summary>
        internal static string validation_duplicatedEntry
        {
            get
            {
                return ResourceManager.GetString("validation.duplicatedEntry", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email address is not unique..
        /// </summary>
        internal static string validation_emailIsNotUnique
        {
            get
            {
                return ResourceManager.GetString("validation.emailIsNotUnique", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than 0..
        /// </summary>
        internal static string validation_greaterThanZero
        {
            get
            {
                return ResourceManager.GetString("validation.greaterThanZero", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to In selected work center machine with this code already existing..
        /// </summary>
        internal static string validation_inThisWorkCenterMachineWiththisCodeAlreadyExisting
        {
            get
            {
                return ResourceManager.GetString("validation.inThisWorkCenterMachineWiththisCodeAlreadyExisting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid email address..
        /// </summary>
        internal static string validation_invalidEmail
        {
            get
            {
                return ResourceManager.GetString("validation.invalidEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Login is not unique..
        /// </summary>
        internal static string validation_loginIsNotUnique
        {
            get
            {
                return ResourceManager.GetString("validation.loginIsNotUnique", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decimal digits cannot be greater or equal {{maxDecimalDigits}}..
        /// </summary>
        internal static string validation_maxDecimalDigits
        {
            get
            {
                return ResourceManager.GetString("validation.maxDecimalDigits", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max field length is {{ maxLength }} characters..
        /// </summary>
        internal static string validation_maxLength
        {
            get
            {
                return ResourceManager.GetString("validation.maxLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Field value can be greater than {{ maxValue }}..
        /// </summary>
        internal static string validation_maxValue
        {
            get
            {
                return ResourceManager.GetString("validation.maxValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Field value can be lower than {{ minValue }}..
        /// </summary>
        internal static string validation_minValue
        {
            get
            {
                return ResourceManager.GetString("validation.minValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name is not unique..
        /// </summary>
        internal static string validation_nameIsNotUnique
        {
            get
            {
                return ResourceManager.GetString("validation.nameIsNotUnique", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Field value is not correct number..
        /// </summary>
        internal static string validation_number
        {
            get
            {
                return ResourceManager.GetString("validation.number", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operation is not unique..
        /// </summary>
        internal static string validation_operationIsNotUnique
        {
            get
            {
                return ResourceManager.GetString("validation.operationIsNotUnique", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The pattern is not match {{ regEx }}.
        /// </summary>
        internal static string validation_regex
        {
            get
            {
                return ResourceManager.GetString("validation.regex", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Field is required..
        /// </summary>
        internal static string validation_required
        {
            get
            {
                return ResourceManager.GetString("validation.required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Start date should not be later than end date..
        /// </summary>
        internal static string validation_startDateShouldNotBeLaterThanEndDate
        {
            get
            {
                return ResourceManager.GetString("validation.startDateShouldNotBeLaterThanEndDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value is not unique..
        /// </summary>
        internal static string validation_valueIsNotUnique
        {
            get
            {
                return ResourceManager.GetString("validation.valueIsNotUnique", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Valid from date.
        /// </summary>
        internal static string validFromDate
        {
            get
            {
                return ResourceManager.GetString("validFromDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        internal static string value
        {
            get
            {
                return ResourceManager.GetString("value", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        internal static string visible
        {
            get
            {
                return ResourceManager.GetString("visible", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Warehouse.
        /// </summary>
        internal static string warehouse
        {
            get
            {
                return ResourceManager.GetString("warehouse", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Worker.
        /// </summary>
        internal static string worker
        {
            get
            {
                return ResourceManager.GetString("worker", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes
        {
            get
            {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
