//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOR.Resources.FrontEndTranslations.Common
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Login
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Login()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFC.Resources.Frontend.Common.Login", typeof(Login).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string changePassword
        {
            get
            {
                return ResourceManager.GetString("changePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string confirmNewPassword
        {
            get
            {
                return ResourceManager.GetString("confirmNewPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string currentPassword
        {
            get
            {
                return ResourceManager.GetString("currentPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Force password change.
        /// </summary>
        internal static string forcePasswordChange
        {
            get
            {
                return ResourceManager.GetString("forcePasswordChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to force this user to change the password?.
        /// </summary>
        internal static string forcePasswordChangeConfirmationMessage
        {
            get
            {
                return ResourceManager.GetString("forcePasswordChangeConfirmationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User is not active..
        /// </summary>
        internal static string inactiveUser
        {
            get
            {
                return ResourceManager.GetString("inactiveUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid login or password..
        /// </summary>
        internal static string invalidLoginOrPassword
        {
            get
            {
                return ResourceManager.GetString("invalidLoginOrPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string newPassword
        {
            get
            {
                return ResourceManager.GetString("newPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password change is required..
        /// </summary>
        internal static string passwordChangeRequired
        {
            get
            {
                return ResourceManager.GetString("passwordChangeRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password reset.
        /// </summary>
        internal static string passwordReset
        {
            get
            {
                return ResourceManager.GetString("passwordReset", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Passwords don&apos;t match..
        /// </summary>
        internal static string passwordsNotMatch
        {
            get
            {
                return ResourceManager.GetString("passwordsNotMatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please sign in.
        /// </summary>
        internal static string pleaseSignIn
        {
            get
            {
                return ResourceManager.GetString("pleaseSignIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string resetPassword
        {
            get
            {
                return ResourceManager.GetString("resetPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to reset the password for this user?.
        /// </summary>
        internal static string resetPasswordConfirmationMessage
        {
            get
            {
                return ResourceManager.GetString("resetPasswordConfirmationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string signIn
        {
            get
            {
                return ResourceManager.GetString("signIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign out.
        /// </summary>
        internal static string signOut
        {
            get
            {
                return ResourceManager.GetString("signOut", resourceCulture);
            }
        }
    }
}
