//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOR.Resources.FrontEndTranslations.Statuses
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RoutingStatusChange
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoutingStatusChange()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFC.Resources.Frontend.Statuses.RoutingStatusChange", typeof(RoutingStatusChange).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string confirm
        {
            get
            {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New routing status.
        /// </summary>
        public static string newRoutingStatus
        {
            get
            {
                return ResourceManager.GetString("newRoutingStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New work order status.
        /// </summary>
        public static string newWorkOrderStatus
        {
            get
            {
                return ResourceManager.GetString("newWorkOrderStatus", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string next
        {
            get
            {
                return ResourceManager.GetString("next", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Opened routings list.
        /// </summary>
        public static string pageTitleActivity
        {
            get
            {
                return ResourceManager.GetString("pageTitleActivity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Routing status change.
        /// </summary>
        public static string pageTitleRoutingStatusChange
        {
            get
            {
                return ResourceManager.GetString("pageTitleRoutingStatusChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        public static string routingStart
        {
            get
            {
                return ResourceManager.GetString("routingStart", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Routing status change has been confirmed successfully.
        /// </summary>
        public static string savedSuccessfully
        {
            get
            {
                return ResourceManager.GetString("savedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Update quantities.
        /// </summary>
        public static string updateQuantities
        {
            get
            {
                return ResourceManager.GetString("updateQuantities", resourceCulture);
            }
        }
    }
}
