//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOR.Resources.FrontEndTranslations.Statuses
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatusReason
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatusReason()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFC.Resources.Frontend.Statuses.StatusReason", typeof(StatusReason).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add new status reason.
        /// </summary>
        public static string addNewStatusReason
        {
            get
            {
                return ResourceManager.GetString("addNewStatusReason", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string color
        {
            get
            {
                return ResourceManager.GetString("color", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Charged department.
        /// </summary>
        public static string nonProductive_chargedDepartment
        {
            get
            {
                return ResourceManager.GetString("nonProductive.chargedDepartment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reject reason.
        /// </summary>
        public static string nonProductive_rejectReason
        {
            get
            {
                return ResourceManager.GetString("nonProductive.rejectReason", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status reasons list.
        /// </summary>
        public static string pageTitle
        {
            get
            {
                return ResourceManager.GetString("pageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reference code.
        /// </summary>
        public static string referenceCode
        {
            get
            {
                return ResourceManager.GetString("referenceCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove {COUNT, plural, one{this status reason} other{these status reasons} }?.
        /// </summary>
        public static string removeConfirmationMessage
        {
            get
            {
                return ResourceManager.GetString("removeConfirmationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status reason has been saved successfully..
        /// </summary>
        public static string savedSuccessfully
        {
            get
            {
                return ResourceManager.GetString("savedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Status reason master code.
        /// </summary>
        public static string statusReasonCode
        {
            get
            {
                return ResourceManager.GetString("statusReasonCode", resourceCulture);
            }
        }
    }
}
