//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOR.Resources.FrontEndTranslations.Machines
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Machine
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Machine()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFC.Resources.Frontend.Machines.Machine", typeof(Machine).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activity mode.
        /// </summary>
        internal static string activityMode
        {
            get
            {
                return ResourceManager.GetString("activityMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string department
        {
            get
            {
                return ResourceManager.GetString("department", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to External code.
        /// </summary>
        internal static string externalCode
        {
            get
            {
                return ResourceManager.GetString("externalCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to External code export.
        /// </summary>
        internal static string externalCodeExport
        {
            get
            {
                return ResourceManager.GetString("externalCodeExport", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Machines list.
        /// </summary>
        internal static string machineList
        {
            get
            {
                return ResourceManager.GetString("machineList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Max activities.
        /// </summary>
        internal static string maxActivities
        {
            get
            {
                return ResourceManager.GetString("maxActivities", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Machine.
        /// </summary>
        internal static string name
        {
            get
            {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Number series.
        /// </summary>
        internal static string numberSeries
        {
            get
            {
                return ResourceManager.GetString("numberSeries", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Only production line.
        /// </summary>
        internal static string onlyProductionLine
        {
            get
            {
                return ResourceManager.GetString("onlyProductionLine", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resource group.
        /// </summary>
        internal static string resourceGroup
        {
            get
            {
                return ResourceManager.GetString("resourceGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Machine have been updated..
        /// </summary>
        internal static string savedSuccessfully
        {
            get
            {
                return ResourceManager.GetString("savedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Slots.
        /// </summary>
        internal static string slots
        {
            get
            {
                return ResourceManager.GetString("slots", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to This work center has more than one resource group..
        /// </summary>
        internal static string validation_multipleResourceGroup
        {
            get
            {
                return ResourceManager.GetString("validation.multipleResourceGroup", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Work center.
        /// </summary>
        internal static string workCenter
        {
            get
            {
                return ResourceManager.GetString("workCenter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parallel work on multiple orders.
        /// </summary>
        internal static string workOnMultipleOrders
        {
            get
            {
                return ResourceManager.GetString("workOnMultipleOrders", resourceCulture);
            }
        }
    }
}
