//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOR.Resources.FrontEndTranslations.Administration
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigurationParameters
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationParameters()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFC.Resources.Frontend.Administration.ConfigurationParameters", typeof(ConfigurationParameters).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string _false
        {
            get
            {
                return ResourceManager.GetString("false", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string _true
        {
            get
            {
                return ResourceManager.GetString("true", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bool value.
        /// </summary>
        internal static string boolValue
        {
            get
            {
                return ResourceManager.GetString("boolValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string code
        {
            get
            {
                return ResourceManager.GetString("code", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration parameter.
        /// </summary>
        internal static string configurationParameter
        {
            get
            {
                return ResourceManager.GetString("configurationParameter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Configuration parameters list.
        /// </summary>
        internal static string configurationParametersList
        {
            get
            {
                return ResourceManager.GetString("configurationParametersList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Decimal value.
        /// </summary>
        internal static string decimalValue
        {
            get
            {
                return ResourceManager.GetString("decimalValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description
        {
            get
            {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Force close Machine Activity.
        /// </summary>
        internal static string ForceCloseMachineActivity
        {
            get
            {
                return ResourceManager.GetString("ForceCloseMachineActivity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string name
        {
            get
            {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string no
        {
            get
            {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parallel work.
        /// </summary>
        internal static string ParallelEmpActivityNotAllowed
        {
            get
            {
                return ResourceManager.GetString("ParallelEmpActivityNotAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter name.
        /// </summary>
        internal static string parameterName
        {
            get
            {
                return ResourceManager.GetString("parameterName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Parameter type.
        /// </summary>
        internal static string parameterType
        {
            get
            {
                return ResourceManager.GetString("parameterType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Machine mapping to external code.
        /// </summary>
        internal static string PortalMachineMappingToExternalCode
        {
            get
            {
                return ResourceManager.GetString("PortalMachineMappingToExternalCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string PortalMachineMappingToExternalCode0
        {
            get
            {
                return ResourceManager.GetString("PortalMachineMappingToExternalCode0", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string PortalMachineMappingToExternalCode1
        {
            get
            {
                return ResourceManager.GetString("PortalMachineMappingToExternalCode1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to change of status of operation for all workers which taking a part in this operation. .
        /// </summary>
        internal static string PortalMassOperationStatusChange
        {
            get
            {
                return ResourceManager.GetString("PortalMassOperationStatusChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Portal mass qty exceed allowable.
        /// </summary>
        internal static string PortalMassQtyExceedAllowable
        {
            get
            {
                return ResourceManager.GetString("PortalMassQtyExceedAllowable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Portal mass status change qty adjustment.
        /// </summary>
        internal static string PortalMassStatusChangeQtyAdjustment
        {
            get
            {
                return ResourceManager.GetString("PortalMassStatusChangeQtyAdjustment", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Portal mass WO status change.
        /// </summary>
        internal static string PortalMassWOStatusChange
        {
            get
            {
                return ResourceManager.GetString("PortalMassWOStatusChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Portal permission to change date.
        /// </summary>
        internal static string PortalPermissionToChangeDate
        {
            get
            {
                return ResourceManager.GetString("PortalPermissionToChangeDate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registering qty in terminal is allowed.
        /// </summary>
        internal static string RegisteringQtyInTerminalIsAllowed
        {
            get
            {
                return ResourceManager.GetString("RegisteringQtyInTerminalIsAllowed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Selected value.
        /// </summary>
        internal static string selectedValue
        {
            get
            {
                return ResourceManager.GetString("selectedValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal bar code separator.
        /// </summary>
        internal static string TerminalBarCodeSeparator
        {
            get
            {
                return ResourceManager.GetString("TerminalBarCodeSeparator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Availability of break button in terminal.
        /// </summary>
        internal static string TerminalBreakButtonIsAvailable
        {
            get
            {
                return ResourceManager.GetString("TerminalBreakButtonIsAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Availability of brigade button in terminal.
        /// </summary>
        internal static string TerminalBrigadeButtonIsAvailable
        {
            get
            {
                return ResourceManager.GetString("TerminalBrigadeButtonIsAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal close activity button availability.
        /// </summary>
        internal static string TerminalCloseActivityButtonIsAvailable
        {
            get
            {
                return ResourceManager.GetString("TerminalCloseActivityButtonIsAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Way to close all machine activities.
        /// </summary>
        internal static string TerminalCloseAllMachineActivity
        {
            get
            {
                return ResourceManager.GetString("TerminalCloseAllMachineActivity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Not possible to close activity by button.
        /// </summary>
        internal static string TerminalCloseAllMachineActivity1
        {
            get
            {
                return ResourceManager.GetString("TerminalCloseAllMachineActivity1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close of activities without questioning.
        /// </summary>
        internal static string TerminalCloseAllMachineActivity2
        {
            get
            {
                return ResourceManager.GetString("TerminalCloseAllMachineActivity2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close of activities with questioning.
        /// </summary>
        internal static string TerminalCloseAllMachineActivity3
        {
            get
            {
                return ResourceManager.GetString("TerminalCloseAllMachineActivity3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string TerminalCloseAllMachineActivity4
        {
            get
            {
                return ResourceManager.GetString("TerminalCloseAllMachineActivity4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal end work frozen time.
        /// </summary>
        internal static string TerminalEndWorkFrozenTime
        {
            get
            {
                return ResourceManager.GetString("TerminalEndWorkFrozenTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TerminalIdleTimout.
        /// </summary>
        internal static string TerminalIdleTimout
        {
            get
            {
                return ResourceManager.GetString("TerminalIdleTimout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal max shift time.
        /// </summary>
        internal static string TerminalMaxShiftTime
        {
            get
            {
                return ResourceManager.GetString("TerminalMaxShiftTime", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal max shift time close mode.
        /// </summary>
        internal static string TerminalMaxShiftTimeCloseMode
        {
            get
            {
                return ResourceManager.GetString("TerminalMaxShiftTimeCloseMode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Worker have to finished shift himself and is not able to start new activity on this shift..
        /// </summary>
        internal static string TerminalMaxShiftTimeCloseMode0
        {
            get
            {
                return ResourceManager.GetString("TerminalMaxShiftTimeCloseMode0", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Automatically finishing shift with actual time..
        /// </summary>
        internal static string TerminalMaxShiftTimeCloseMode1
        {
            get
            {
                return ResourceManager.GetString("TerminalMaxShiftTimeCloseMode1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Availability of non productive button in terminal.
        /// </summary>
        internal static string TerminalNonProductiveButtonIsAvailable
        {
            get
            {
                return ResourceManager.GetString("TerminalNonProductiveButtonIsAvailable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal order operation scan change.
        /// </summary>
        internal static string TerminalOrderOperationScanChange
        {
            get
            {
                return ResourceManager.GetString("TerminalOrderOperationScanChange", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Many orders..
        /// </summary>
        internal static string TerminalOrderOperationScanChange1
        {
            get
            {
                return ResourceManager.GetString("TerminalOrderOperationScanChange1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Single order..
        /// </summary>
        internal static string TerminalOrderOperationScanChange2
        {
            get
            {
                return ResourceManager.GetString("TerminalOrderOperationScanChange2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal print label availbility button.
        /// </summary>
        internal static string TerminalPrintLabel
        {
            get
            {
                return ResourceManager.GetString("TerminalPrintLabel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal shift delta.
        /// </summary>
        internal static string TerminalShiftDelta
        {
            get
            {
                return ResourceManager.GetString("TerminalShiftDelta", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terminal work activity choice.
        /// </summary>
        internal static string TerminalWorkActivityChoice
        {
            get
            {
                return ResourceManager.GetString("TerminalWorkActivityChoice", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to After start activity redirecting to list..
        /// </summary>
        internal static string TerminalWorkActivityChoice1
        {
            get
            {
                return ResourceManager.GetString("TerminalWorkActivityChoice1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to After start activity automatically logging out..
        /// </summary>
        internal static string TerminalWorkActivityChoice2
        {
            get
            {
                return ResourceManager.GetString("TerminalWorkActivityChoice2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to After start activity coming up validation window then automatically redirecting to list..
        /// </summary>
        internal static string TerminalWorkActivityChoice3
        {
            get
            {
                return ResourceManager.GetString("TerminalWorkActivityChoice3", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to After start activity coming up validation window then automatically logging out..
        /// </summary>
        internal static string TerminalWorkActivityChoice4
        {
            get
            {
                return ResourceManager.GetString("TerminalWorkActivityChoice4", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string text
        {
            get
            {
                return ResourceManager.GetString("text", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text value.
        /// </summary>
        internal static string textValue
        {
            get
            {
                return ResourceManager.GetString("textValue", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string yes
        {
            get
            {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
