//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOR.Resources.FrontEndTranslations.Administration
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PowerBiDefinition
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PowerBiDefinition()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFC.Resources.Frontend.Administration.PowerBiDefinition", typeof(PowerBiDefinition).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add new Power BI component.
        /// </summary>
        public static string addNewPowerBiDefinition
        {
            get
            {
                return ResourceManager.GetString("addNewPowerBiDefinition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Power BI component.
        /// </summary>
        public static string component
        {
            get
            {
                return ResourceManager.GetString("component", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Power BI components.
        /// </summary>
        public static string components
        {
            get
            {
                return ResourceManager.GetString("components", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Default Power BI component.
        /// </summary>
        public static string defaultPowerBiDefinition
        {
            get
            {
                return ResourceManager.GetString("defaultPowerBiDefinition", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Power BI components list.
        /// </summary>
        public static string pageTitle
        {
            get
            {
                return ResourceManager.GetString("pageTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove {COUNT, plural, one{this Power BI component} other{these Power BI components} }?.
        /// </summary>
        public static string removeConfirmationMessage
        {
            get
            {
                return ResourceManager.GetString("removeConfirmationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Power BI component has been saved successfully..
        /// </summary>
        public static string savedSuccessfully
        {
            get
            {
                return ResourceManager.GetString("savedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User Power BI definitions list.
        /// </summary>
        public static string userPowerBiDefinitionList
        {
            get
            {
                return ResourceManager.GetString("userPowerBiDefinitionList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User Power BI definitions have been saved successfully..
        /// </summary>
        public static string usrPbiSavedSuccessfully
        {
            get
            {
                return ResourceManager.GetString("usrPbiSavedSuccessfully", resourceCulture);
            }
        }
    }
}
