//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOR.Resources.FrontEndTranslations.Parts
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PartAttributeSet
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PartAttributeSet()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFC.Resources.Frontend.Parts.PartAttributeSet", typeof(PartAttributeSet).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string attribute
        {
            get
            {
                return ResourceManager.GetString("attribute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attribute sets.
        /// </summary>
        internal static string attributeSets
        {
            get
            {
                return ResourceManager.GetString("attributeSets", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Key attribute.
        /// </summary>
        internal static string keyAttribute
        {
            get
            {
                return ResourceManager.GetString("keyAttribute", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to There is no attributes.
        /// </summary>
        internal static string noAttributes
        {
            get
            {
                return ResourceManager.GetString("noAttributes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to change the attribute set?.
        /// </summary>
        internal static string saveConfirmationMessage
        {
            get
            {
                return ResourceManager.GetString("saveConfirmationMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Attribute set has been updated..
        /// </summary>
        internal static string savedSuccessfully
        {
            get
            {
                return ResourceManager.GetString("savedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Some attributes are marked for deletion.
        /// </summary>
        internal static string saveWarningMessage
        {
            get
            {
                return ResourceManager.GetString("saveWarningMessage", resourceCulture);
            }
        }
    }
}
