//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOR.Resources.FrontEndTranslations.Parts
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Part
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Part()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SFC.Resources.Frontend.Parts.Part", typeof(Part).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Index description.
        /// </summary>
        internal static string description
        {
            get
            {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Lot control.
        /// </summary>
        internal static string lotRequired
        {
            get
            {
                return ResourceManager.GetString("lotRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        internal static string name
        {
            get
            {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Index list.
        /// </summary>
        internal static string partList
        {
            get
            {
                return ResourceManager.GetString("partList", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Part have been updated..
        /// </summary>
        internal static string savedSuccessfully
        {
            get
            {
                return ResourceManager.GetString("savedSuccessfully", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Serial control.
        /// </summary>
        internal static string serialRequired
        {
            get
            {
                return ResourceManager.GetString("serialRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unit measure.
        /// </summary>
        internal static string unitMeasure
        {
            get
            {
                return ResourceManager.GetString("unitMeasure", resourceCulture);
            }
        }
    }
}
